### ISSUE TITLE
yaml-mode indentation issues

### ISSUE THREAD

**Issue by base698** [joaotavora/yasnippet#1020]
This mass indents at every new line.  Is there a way to turn that behavior off, or turn off the major mode?  

```
# -*- mode: snippet -*-
# name: service
# key: svc
# --
kind: Service
apiVersion: v1
metadata:
  labels:
    app: $0
  name: $1
spec:
  ports:
    - port: $2
      protocol: $3
      targetPort: $4
      name: $5
  selector:
    app: $6
```

Results in:
```
kind: Service
apiVersion: v1
metadata:
  labels:
    app: 
      name: 
        spec:
          ports:
            - port: 
                protocol: 
                  targetPort: 
                    name: 
                      selector:
                        app: 

```
